#!/bin/bash
################################################################################
################################################################################


MYIPADDR=$(/sbin/ifconfig | grep "netmask" | grep -v "127.0.0.1" | awk '{ print $2 ":8001" }' )

cd $HOME/eoswallet

git pull

killall -9 keosd
killall -9 php
echo "" > ./phpd.log
echo "" > ./start_info.txt
./bin/keosd --http-server-address=127.0.0.1:5555 "$@" > ./wallet-stdout.txt 2> ./wallet-stderr.txt  & echo $! > $HOME/eoswallet/wallet.pid
./cleos get info > start_info.txt
nohup php -S $MYIPADDR -t $HOME/eoswallet > $HOME/eoswallet/phpd.log 2>&1 &


