#!/bin/bash
################################################################################
################################################################################


killall -9 keosd
killall -9 php
echo "" > ./phpd.log
echo "" > ./start_info.txt
./bin/keosd --http-server-address=127.0.0.1:5555 "$@" > ./wallet-stdout.txt 2> ./wallet-stderr.txt  & echo $! > ./wallet.pid
./cleos get info > start_info.txt
nohup php -S localhost:8002 -t ./ > ./phpd.log 2>&1 &
echo "open your browser and go to address: http://localhost:8002"


